version: 2.1

executors:
  node_executor:
    docker:
      - image: circleci/node:12.14.1

commands:
  setup_environment:
    executor: node_executor
    steps:
      - checkout
      - npm run install


jobs:
  unit-tests:
    executor: node_executor
    - setup_environment
    steps:
      - run: npm run lint
      - run: npm run test

      
workflows:
  wizards-brew-frontend:
    jobs:
      - unit-tests
