version: 2.1

executors:
  node_executor:
    docker:
      - image: circleci/node:12.14.1

commands:
  setup_environment:
    steps:
      - checkout
      - npm run install

jobs:
  unit-tests:
    executor: node_executor
    - setup_environment
    steps:
      - run: npm run lint
      - run: npm run test
