version: 2.1

jobs:
  Run lint:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - run: npm run lint

orbs:
  node: circleci/node@3.0.0
workflows:
  wizards-brew-frontend:
    jobs:
      - node/test
      - Run lint
