version: 2.1

executors:
  node_executor:
    docker:
      - image: circleci/node:12.14.1

commands:
  setup_environment:
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install

jobs:
  unit-tests:
    executor: node_executor
    steps:
      - setup_environment 
      - run: npm run lint
      - run: npm run test

orbs:
  node: circleci/node@3.0.0      
workflows:
  wizards-brew-frontend:
    jobs:
      - unit-tests
