version: 2.1

executors:
  node_executor:
    docker:
      - image: circleci/node:12.14.1

jobs:
  Run lint:
    executor: node_executor
    steps:
      - run: npm run lint

orbs:
  node: circleci/node@4.1.0
workflows:
  wizards-brew-frontend:
    jobs:
      - node/test
      - Run lint
